# Generated by Django 5.2.6 on 2025-09-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_taskcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
