# Generated by Django 5.2.6 on 2025-09-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_project_team_members_user_is_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_team_member',
        ),
    ]
